# Generated by Django 5.2.6 on 2025-09-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.TextField()),
                ('motivo_de_visita', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_visita', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
