# Generated by Django 5.2.6 on 2025-09-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_visita_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='motivo_de_visita',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
